spring:
  application:
    name: trash-core
  datasource:
    url: jdbc:postgresql://localhost:5432/trash
    username: postgres
    password: can
  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n/messages

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    enabled: true
    path: /swagger

scalar:
  url: http://localhost:8080/openapi.json
  path: /scalar
  enabled: true

app:
  jwt:
    secret: yImRb4CB0OtJcs74Lpzv9WcfoEFnqxVnyImRb4CB0OtJcs74Lpzv9WcfoEFnqxVnyImRb4CB0OtJcs74Lpzv9WcfoEFnqxVn